# GitHub Sponsors and other funding links for QoreDB
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [QoreDB]
custom:
  - https://www.qoredb.com/pricing
  - https://www.qoredb.com/newsletter
