// SPDX-License-Identifier: Apache-2.0

import type { CellResult, QoreNotebook } from './notebookTypes';

/**
 * Export a notebook to Markdown format.
 */
export function exportToMarkdown(notebook: QoreNotebook, includeResults = false): string {
  const parts: string[] = [];

  parts.push(`# ${notebook.metadata.title}\n`);
  if (notebook.metadata.description) {
    parts.push(`${notebook.metadata.description}\n`);
  }

  for (const cell of notebook.cells) {
    if (cell.type === 'markdown') {
      parts.push(cell.source);
    } else if (cell.type === 'sql' || cell.type === 'mongo') {
      parts.push(`\`\`\`sql\n${cell.source}\n\`\`\``);
      if (includeResults && cell.lastResult) {
        const table = resultToMarkdownTable(cell.lastResult);
        if (table) parts.push(table);
      }
    }
    parts.push(''); // blank line separator
  }

  return parts.join('\n').trim() + '\n';
}

/**
 * Export a notebook to standalone HTML.
 */
export function exportToHtml(notebook: QoreNotebook, includeResults = false): string {
  const cellsHtml = notebook.cells
    .map(cell => {
      if (cell.type === 'markdown') {
        return `<div class="cell cell-markdown">${escapeHtml(cell.source)}</div>`;
      }
      if (cell.type === 'sql' || cell.type === 'mongo') {
        let html = `<div class="cell cell-sql"><pre><code>${escapeHtml(cell.source)}</code></pre>`;
        if (includeResults && cell.lastResult) {
          html += resultToHtmlTable(cell.lastResult);
        }
        html += '</div>';
        return html;
      }
      return '';
    })
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(notebook.metadata.title)}</title>
<style>
  :root { --bg: #fff; --fg: #0e1116; --border: #dde0e5; --code-bg: #f6f7f9; --accent: #6b5cff; }
  @media (prefers-color-scheme: dark) {
    :root { --bg: #0b0c0f; --fg: #f4f6fa; --border: #2a2d35; --code-bg: #14151a; --accent: #7a6cff; }
  }
  body { font-family: Inter, system-ui, sans-serif; background: var(--bg); color: var(--fg); max-width: 900px; margin: 0 auto; padding: 2rem; line-height: 1.6; }
  h1 { font-size: 1.5rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }
  .cell { margin: 1rem 0; }
  .cell-sql pre { background: var(--code-bg); border: 1px solid var(--border); border-radius: 6px; padding: 1rem; overflow-x: auto; }
  .cell-sql code { font-family: 'JetBrains Mono', 'Fira Code', monospace; font-size: 0.875rem; }
  .cell-markdown { white-space: pre-wrap; }
  table { border-collapse: collapse; width: 100%; margin-top: 0.5rem; font-size: 0.8rem; }
  th, td { border: 1px solid var(--border); padding: 4px 8px; text-align: left; }
  th { background: var(--code-bg); font-weight: 600; }
  .meta { color: #8a90a0; font-size: 0.75rem; margin-top: 0.5rem; }
</style>
</head>
<body>
<h1>${escapeHtml(notebook.metadata.title)}</h1>
${notebook.metadata.description ? `<p>${escapeHtml(notebook.metadata.description)}</p>` : ''}
${cellsHtml}
<p class="meta">Generated by QoreDB on ${new Date().toISOString().split('T')[0]}</p>
</body>
</html>`;
}

function resultToMarkdownTable(result: CellResult, maxRows = 20): string | null {
  if (result.type === 'message') return `> ${result.message}`;
  if (result.type === 'error') return `> **Error:** ${result.error}`;
  if (result.type !== 'table' || !result.columns || !result.rows) return null;

  const cols = result.columns;
  const rows = result.rows.slice(0, maxRows);

  const header = '| ' + cols.map(c => c.name).join(' | ') + ' |';
  const separator = '| ' + cols.map(() => '---').join(' | ') + ' |';
  const body = rows
    .map(row => '| ' + cols.map((_, i) => String(row.values[i] ?? '')).join(' | ') + ' |')
    .join('\n');

  let table = [header, separator, body].join('\n');
  if (result.rows.length > maxRows) {
    table += `\n\n*Showing ${maxRows} of ${result.rows.length} rows*`;
  }
  return table;
}

function resultToHtmlTable(result: CellResult, maxRows = 50): string {
  if (result.type === 'message') return `<p class="meta">${escapeHtml(result.message ?? '')}</p>`;
  if (result.type === 'error') return `<p style="color:red">${escapeHtml(result.error ?? '')}</p>`;
  if (result.type !== 'table' || !result.columns || !result.rows) return '';

  const cols = result.columns;
  const rows = result.rows.slice(0, maxRows);

  const headerHtml = cols.map(c => `<th>${escapeHtml(c.name)}</th>`).join('');
  const bodyHtml = rows
    .map(
      row =>
        '<tr>' +
        cols.map((_, i) => `<td>${escapeHtml(String(row.values[i] ?? ''))}</td>`).join('') +
        '</tr>'
    )
    .join('\n');

  let html = `<table><thead><tr>${headerHtml}</tr></thead><tbody>${bodyHtml}</tbody></table>`;
  if (result.rows.length > maxRows) {
    html += `<p class="meta">Showing ${maxRows} of ${result.rows.length} rows</p>`;
  }
  return html;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
