// SPDX-License-Identifier: Apache-2.0

//! Drivers whose raw-SQL DDL the migrations runner can apply. Excludes
//! document/KV/search stores and ClickHouse (non-standard transactions/DDL).

export const SCHEMA_MIGRATION_DRIVERS = new Set([
  'postgres',
  'cockroachdb',
  'yugabytedb',
  'mysql',
  'mariadb',
  'planetscale',
  'tidb',
  'starrocks',
  'doris',
  'singlestore',
  'sqlite',
  'duckdb',
  'motherduck',
  'sqlserver',
  'azuresql',
  'synapse',
  'timescaledb',
  'supabase',
  'neon',
]);

/** Drivers whose table DDL can also be generated by the schema-diff builders. */
export const SCHEMA_DIFF_DRIVERS = new Set(
  [...SCHEMA_MIGRATION_DRIVERS].filter(
    driver => driver !== 'starrocks' && driver !== 'doris' && driver !== 'synapse'
  )
);

/** DDL auto-commits here, so a failed migration can't be fully rolled back. */
export const NON_TX_DDL_DRIVERS = new Set([
  'mysql',
  'mariadb',
  'planetscale',
  'tidb',
  'starrocks',
  'doris',
  'singlestore',
]);
