// SPDX-License-Identifier: Apache-2.0

import { Driver } from '../connection/drivers';
import type { ColumnType } from './types';

const POSTGRES_TYPES: ColumnType[] = [
  { name: 'SERIAL', category: 'integer', isAutoIncrement: true },
  { name: 'BIGSERIAL', category: 'integer', isAutoIncrement: true },
  { name: 'SMALLINT', category: 'integer' },
  { name: 'INTEGER', category: 'integer' },
  { name: 'BIGINT', category: 'integer' },
  { name: 'REAL', category: 'float' },
  { name: 'DOUBLE PRECISION', category: 'float' },
  { name: 'NUMERIC', category: 'float', hasPrecision: true },
  { name: 'DECIMAL', category: 'float', hasPrecision: true },
  { name: 'VARCHAR', category: 'string', hasLength: true },
  { name: 'CHAR', category: 'string', hasLength: true },
  { name: 'TEXT', category: 'text' },
  { name: 'DATE', category: 'date' },
  { name: 'TIME', category: 'date' },
  { name: 'TIMESTAMP', category: 'date' },
  { name: 'TIMESTAMPTZ', category: 'date' },
  { name: 'BOOLEAN', category: 'boolean' },
  { name: 'UUID', category: 'other' },
  { name: 'BYTEA', category: 'binary' },
  { name: 'JSON', category: 'json' },
  { name: 'JSONB', category: 'json' },
];

const MYSQL_TYPES: ColumnType[] = [
  { name: 'TINYINT', category: 'integer' },
  { name: 'SMALLINT', category: 'integer' },
  { name: 'MEDIUMINT', category: 'integer' },
  { name: 'INT', category: 'integer' },
  { name: 'BIGINT', category: 'integer' },
  { name: 'FLOAT', category: 'float' },
  { name: 'DOUBLE', category: 'float' },
  { name: 'DECIMAL', category: 'float', hasPrecision: true },
  { name: 'VARCHAR', category: 'string', hasLength: true },
  { name: 'CHAR', category: 'string', hasLength: true },
  { name: 'TEXT', category: 'text' },
  { name: 'MEDIUMTEXT', category: 'text' },
  { name: 'LONGTEXT', category: 'text' },
  { name: 'DATE', category: 'date' },
  { name: 'TIME', category: 'date' },
  { name: 'DATETIME', category: 'date' },
  { name: 'TIMESTAMP', category: 'date' },
  { name: 'BOOLEAN', category: 'boolean' },
  { name: 'BLOB', category: 'binary' },
  { name: 'JSON', category: 'json' },
];

const SQLITE_TYPES: ColumnType[] = [
  { name: 'INTEGER', category: 'integer' },
  { name: 'INT', category: 'integer' },
  { name: 'BIGINT', category: 'integer' },
  { name: 'SMALLINT', category: 'integer' },
  { name: 'TINYINT', category: 'integer' },
  { name: 'REAL', category: 'float' },
  { name: 'DOUBLE', category: 'float' },
  { name: 'FLOAT', category: 'float' },
  { name: 'NUMERIC', category: 'float', hasPrecision: true },
  { name: 'DECIMAL', category: 'float', hasPrecision: true },
  { name: 'TEXT', category: 'text' },
  { name: 'VARCHAR', category: 'string', hasLength: true },
  { name: 'CHAR', category: 'string', hasLength: true },
  { name: 'CLOB', category: 'text' },
  { name: 'DATE', category: 'date' },
  { name: 'DATETIME', category: 'date' },
  { name: 'TIMESTAMP', category: 'date' },
  { name: 'BOOLEAN', category: 'boolean' },
  { name: 'BLOB', category: 'binary' },
];

const DUCKDB_TYPES: ColumnType[] = [
  { name: 'TINYINT', category: 'integer' },
  { name: 'SMALLINT', category: 'integer' },
  { name: 'INTEGER', category: 'integer' },
  { name: 'BIGINT', category: 'integer' },
  { name: 'HUGEINT', category: 'integer' },
  { name: 'FLOAT', category: 'float' },
  { name: 'DOUBLE', category: 'float' },
  { name: 'DECIMAL', category: 'float', hasPrecision: true },
  { name: 'VARCHAR', category: 'string', hasLength: true },
  { name: 'TEXT', category: 'text' },
  { name: 'DATE', category: 'date' },
  { name: 'TIME', category: 'date' },
  { name: 'TIMESTAMP', category: 'date' },
  { name: 'TIMESTAMPTZ', category: 'date' },
  { name: 'INTERVAL', category: 'date' },
  { name: 'BOOLEAN', category: 'boolean' },
  { name: 'UUID', category: 'other' },
  { name: 'BLOB', category: 'binary' },
  { name: 'JSON', category: 'json' },
];

const SQLSERVER_TYPES: ColumnType[] = [
  { name: 'TINYINT', category: 'integer' },
  { name: 'SMALLINT', category: 'integer' },
  { name: 'INT', category: 'integer' },
  { name: 'BIGINT', category: 'integer' },
  { name: 'FLOAT', category: 'float' },
  { name: 'REAL', category: 'float' },
  { name: 'DECIMAL', category: 'float', hasPrecision: true },
  { name: 'NUMERIC', category: 'float', hasPrecision: true },
  { name: 'MONEY', category: 'float' },
  { name: 'SMALLMONEY', category: 'float' },
  { name: 'VARCHAR', category: 'string', hasLength: true },
  { name: 'NVARCHAR', category: 'string', hasLength: true },
  { name: 'CHAR', category: 'string', hasLength: true },
  { name: 'NCHAR', category: 'string', hasLength: true },
  { name: 'TEXT', category: 'text' },
  { name: 'NTEXT', category: 'text' },
  { name: 'DATE', category: 'date' },
  { name: 'TIME', category: 'date' },
  { name: 'DATETIME', category: 'date' },
  { name: 'DATETIME2', category: 'date' },
  { name: 'SMALLDATETIME', category: 'date' },
  { name: 'DATETIMEOFFSET', category: 'date' },
  { name: 'BIT', category: 'boolean' },
  { name: 'UNIQUEIDENTIFIER', category: 'other' },
  { name: 'VARBINARY', category: 'binary', hasLength: true },
  { name: 'BINARY', category: 'binary', hasLength: true },
  { name: 'IMAGE', category: 'binary' },
  { name: 'XML', category: 'other' },
];

export const COLUMN_TYPES: Record<Driver, ColumnType[]> = {
  [Driver.Postgres]: POSTGRES_TYPES,
  [Driver.Mysql]: MYSQL_TYPES,
  [Driver.Mongodb]: [],
  [Driver.Redis]: [],
  [Driver.Sqlite]: SQLITE_TYPES,
  [Driver.Duckdb]: DUCKDB_TYPES,
  [Driver.SqlServer]: SQLSERVER_TYPES,
  [Driver.Cockroachdb]: POSTGRES_TYPES,
  [Driver.Mariadb]: MYSQL_TYPES,
  [Driver.Supabase]: POSTGRES_TYPES,
  [Driver.Neon]: POSTGRES_TYPES,
  [Driver.Timescaledb]: POSTGRES_TYPES,
};

export function getColumnTypes(driver: Driver): ColumnType[] {
  return COLUMN_TYPES[driver] || [];
}
